# Jekyll config
title: 7crane | blog
author: Adrian Garza
source: ./blog/
remote_theme: jekyll/minima
show_excerpts: true
minima:
  skin: solarized-dark
  social_links:
    twitter: sevencrane
    github:  garzaa

repository: garzaa/garzaa.github.io
description: ""
