# Jekyll config
title: 7crane | blog
author: Adrian Garza
source: ./blog/
remote_theme: "garzaa/crane-theme"
show_excerpts: true

repository: garzaa/garzaa.github.io
description: ""
archive_page: /blog/index
home_page: /index

plugins:
  - jekyll-remote-theme
